build:pass-test1-fedora:
  image: fedora:latest
  script:
    - cd tests
    - chmod +x ../jobsubmit
    - ../jobsubmit ./cmd.lst all

build:pass-test2-fedora:
  image: fedora:latest
  script:
    - cd tests
    - chmod +x ../jobsubmit 182
    - ../jobsubmit ./cmd.lst


build:pass-test3-fedora:
  image: fedora:latest
  script:
    - cd tests
    - chmod +x ../jobsubmit
    - ../jobsubmit ./cmd.lst 180,1,19,3,5,6,7,8,34,36,234,45,129,32

build:pass-test4-fedora:
  image: fedora:latest
  script:
    - cd tests
    - chmod +x ../jobsubmit
    - ../jobsubmit ./cmd.lst 180-254

build:fail-test1-fedora:
  image: fedora:latest
  script:
    - cd tests
    - chmod +x ../jobsubmit
    - ../jobsubmit ./cmd.lst
