build:test1.fedora:
  image: fedora:latest
  script:
    - chmod +x jobsubmit cleanup ./tests/*.sh
    - cd tests
    - ./run_test.sh
    - cat test1.done

build:test2.fedora:
  image: fedora:latest
  script:
    - chmod +x jobsubmit cleanup ./tests/*.sh
    - cd tests
    - ./run_test.sh
    - cat test2.done

build:test3.fedora:
  image: fedora:latest
  script:
    - chmod +x jobsubmit cleanup ./tests/*.sh
    - cd tests
    - ./run_test.sh
    - cat test3.done

build:test4.fedora:
  image: fedora:latest
  script:
    - chmod +x jobsubmit cleanup ./tests/*.sh
    - cd tests
    - ./run_test.sh
    - cat test4.done
